# Pre-commit per progetto Fullstack (Python 3.9.x + Node.js)
# Include: formatting (black/ruff/prettier), lint (ruff/eslint), import sorting (isort),
# type checking (mypy), security (bandit), patch (pyupgrade),
# and some generic controls.

minimum_pre_commit_version: "3.0.0"

default_stages:
  - pre-commit
  - pre-push

default_language_version:
  python: python3.13

exclude: >
  (?x)^(
    build/|
    dist/|
    \.venv/|
    venv/|
    \.mypy_cache/|
    \.ruff_cache/|
    \.tox/|
    \.eggs/
  )

ci:
  autofix_prs: true
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ["--maxkb=3000"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, css, scss, html, json, markdown]
        additional_dependencies:
          - prettier@3.1.0
          - prettier-plugin-tailwindcss

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.0
    hooks:
      - id: eslint
        files: ^src/core/cloudo-ui/app/.*\.(ts|tsx)$
        additional_dependencies:
          - eslint@9.9.0
          - eslint-config-next@15.0.0
          - typescript@5.5.4
          - "@typescript-eslint/eslint-plugin@8.2.0"
          - "@typescript-eslint/parser@8.2.0"
        args: ["--fix", "--max-warnings", "0", "--config", "src/core/cloudo-ui/eslint.config.mjs"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: ["--fix"]
        language_version: python3.13
      - id: ruff-format
        language_version: python3.13

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        language_version: python3.13

#  - repo: https://github.com/pycqa/bandit
#    rev: 1.7.9
#    hooks:
#      - id: bandit
#        args: ["-r", "."]
#        language_version: python3.13

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]
        language_version: python3.13

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [ "--max-line-length=200" ]
        language_version: python3.13

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - "--args=--enable-rule=terraform_deprecated_interpolation"
      - id: terraform_tfsec
