services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"  # Blob
      - "10001:10001"  # Queue
      - "10002:10002"  # Table
    volumes:
      - azurite_data:/data
    networks:
      - azure-functions

  worker:
    platform: linux/amd64
    build:
      context: ./src/core/worker
      dockerfile: Dockerfile
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1
      - FEATURE_DEV=true
      - DEV_SCRIPT_PATH="/work/runbooks/"
    volumes:
      - ./src/runbooks:/work/runbooks:ro
    ports:
      - "7072:80"
    depends_on:
      - azurite
    networks:
      - azure-functions

  trigger:
    platform: linux/amd64
    build:
      context: ./src/core/orchestrator/trigger
      dockerfile: src/core/orchestrator/Dockerfile
    ports:
      - "7071:80"
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1
    depends_on:
      - azurite
    networks:
      - azure-functions

networks:
  azure-functions:
    driver: bridge

volumes:
  azurite_data:
